package net.practicalcoding.recyclerviewyt

enum class MoleculeId {
                      CLINTON, TRUMP1, TRUMP2, OBAMA, FORD,CARTER,REAGAN,BUSH1,BUSH2,TRUMP,BIDEN,
    ALANINE, ARGININE, ASPARAGINE, ASPARTIC_ACID, CYSTEINE, GLUTAMIC_ACID, GLUTAMINE, GLYCINE,
    HISTIDINE, ISOLEUCINE, LEUCINE, LYSINE, METHIONINE, PHENYLALANINE, PROLINE, SERINE, THREONINE,
    TRYPTOPHAN, TYROSINE, VALINE
}